version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: user_information
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
